name: 'release'

on:
  push:
    branches:
      - 'release'

jobs:
  pre-release:
    name: 'Release'
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Build & test'
        run: |
          npm ci
          npm run build --if-present
          npm run test

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'release'
          # prerelease: true
          title: 'Production Release Build'
          files: |
            *
            .*
